version: "3.8"
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/data

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://host.docker.internal:5000

volumes:
  chromadb_data: